"""HTTPS helpers shared by every network call."""

from __future__ import annotations

import ssl
import urllib.request
from functools import lru_cache

from .platform import is_android


@lru_cache(maxsize=1)
def ssl_context() -> ssl.SSLContext | None:
    """None = Python's default (the system's certificates). On Android there is no system store
    Python can read, so use the CA bundle embedded at build time."""
    if not is_android():
        return None
    try:
        from ._cacerts import PEM  # generated by packaging/android/make_cacerts.py
    except ImportError:
        try:
            import certifi
            return ssl.create_default_context(cafile=certifi.where())
        except ImportError:
            return None
    return ssl.create_default_context(cadata=PEM)


def urlopen(req, timeout: float):
    ctx = ssl_context()
    if ctx is None:
        return urllib.request.urlopen(req, timeout=timeout)
    return urllib.request.urlopen(req, timeout=timeout, context=ctx)
